trigger:
- main
pool: 
   vmImage: ubuntu-latest

variables:
  buildConfigutation: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'